AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: pets_backend SAM Template

Resources:
  # -----------------------------
  # DynamoDB Tables
  # -----------------------------
  AdoptionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: AdoptionsTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  PetsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: PetsTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  # -----------------------------
  # API Gateway
  # -----------------------------
  PetsAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  # -----------------------------
  # Lambda Functions
  # -----------------------------

  GetAdoptionsLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handlers/get_adoptions
      Handler: getAdoptions.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref AdoptionsTable
      Environment:
        Variables:
          ADOPTIONS_TABLE: !Ref AdoptionsTable
      Events:
        GetAdoptionsApi:
          Type: Api
          Properties:
            RestApiId: !Ref PetsAPI
            Path: /adoptions
            Method: get

  GetAdoptionLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handlers/get_adoption
      Handler: getAdoption.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref AdoptionsTable
      Environment:
        Variables:
          ADOPTIONS_TABLE: !Ref AdoptionsTable
      Events:
        GetAdoptionApi:
          Type: Api
          Properties:
            RestApiId: !Ref PetsAPI
            Path: /adoptions/{id}
            Method: get

  CreateAdoptionLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handlers/create_adoption
      Handler: createAdoption.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AdoptionsTable
      Environment:
        Variables:
          ADOPTIONS_TABLE: !Ref AdoptionsTable
      Events:
        CreateAdoptionApi:
          Type: Api
          Properties:
            RestApiId: !Ref PetsAPI
            Path: /adoptions
            Method: post

  GetPetsLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handlers/get_pets
      Handler: getPets.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref PetsTable
      Environment:
        Variables:
          PETS_TABLE: !Ref PetsTable
      Events:
        GetPetsApi:
          Type: Api
          Properties:
            RestApiId: !Ref PetsAPI
            Path: /pets
            Method: get

  UpdateAdoptionLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handlers/update_adoption
      Handler: updateAdoption.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AdoptionsTable
      Environment:
        Variables:
          ADOPTIONS_TABLE: !Ref AdoptionsTable
      Events:
        UpdateAdoptionApi:
          Type: Api
          Properties:
            RestApiId: !Ref PetsAPI
            Path: /adoptions/{id}
            Method: put

# -----------------------------
# Outputs
# -----------------------------
Outputs:
  PetsAPI:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${PetsAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod"

  GetPetsAPIEndpoint:
    Description: "API Gateway endpoint URL for Prod stage for Get Pets function"
    Value: !Sub "https://${PetsAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/pets/"

  GetAdoptionsAPIEndpoint:
    Description: "API Gateway endpoint URL for Prod stage for GetAdoptions function"
    Value: !Sub "https://${PetsAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/adoptions/"

  GetAdoptionAPIEndpoint:
    Description: "API Gateway endpoint URL for Prod stage for GetAdoption function"
    Value: !Sub "https://${PetsAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/adoptions/{id}"

  CreateAdoptionAPIEndpoint:
    Description: "API Gateway endpoint URL for Prod stage for CreateAdoption function"
    Value: !Sub "https://${PetsAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/adoptions/"
